#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaltZone: http://localhost:8761/eureka


spring:
  config:
    import: optional:configserver:http://localhost:8085
  cloud:
    config:
      profile: prod