server:
  port: 8085
spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BansalAakash/SpringMicroservices_ConfigServer
          clone-on-start: true
